In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', 
                   names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'label'])
X = np.array(iris.drop(['label'], axis=1))
y = np.array(iris['label'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
iris.head()

sepal_length  sepal_width  petal_length  petal_width        label
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler().fit(X_train)
print(scaler.mean_)
print(scaler.scale_)
X_train_scaled = scaler.transform(X_train)
X_train_scaled[:5]

[5.80916667 3.0575     3.7275     1.1825    ]
[0.82036535 0.44453393 1.7439401  0.75029578]


array([[-1.47393679,  1.22037928, -1.5639872 , -1.30948358],
       [-0.13307079,  3.02001693, -1.27728011, -1.04292204],
       [ 1.08589829,  0.09560575,  0.38562104,  0.28988568],
       [-1.23014297,  0.77046987, -1.21993869, -1.30948358],
       [-1.7177306 ,  0.32056046, -1.39196294, -1.30948358]])

In [ ]:
X_test_scaled = scaler.transform(X)
X_test_scaled[:5]

array([[-0.86445224,  0.99542457, -1.33462153, -1.30948358],
       [-1.10824606, -0.12934896, -1.33462153, -1.30948358],
       [-1.35203988,  0.32056046, -1.39196294, -1.30948358],
       [-1.47393679,  0.09560575, -1.27728011, -1.30948358],
       [-0.98634915,  1.22037928, -1.33462153, -1.30948358]])

In [ ]:
from sklearn.preprocessing import Normalizer

normalizer = Normalizer(norm='l2') 
X_train_normalized = normalizer.fit_transform(X_train)
X_train_normalized[:5]

array([[0.77577075, 0.60712493, 0.16864581, 0.03372916],
       [0.77381111, 0.59732787, 0.2036345 , 0.05430253],
       [0.76945444, 0.35601624, 0.50531337, 0.16078153],
       [0.786991  , 0.55745196, 0.26233033, 0.03279129],
       [0.78609038, 0.57170209, 0.23225397, 0.03573138]])

In [ ]:
X_test_normalized = normalizer.transform(X_test)
X_test_normalized[:5]

array([[0.73659895, 0.33811099, 0.56754345, 0.14490471],
       [0.8068282 , 0.53788547, 0.24063297, 0.04246464],
       [0.70600618, 0.2383917 , 0.63265489, 0.21088496],
       [0.73350949, 0.35452959, 0.55013212, 0.18337737],
       [0.76467269, 0.31486523, 0.53976896, 0.15743261]])

In [ ]:
y[:5]

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y_le = le.fit_transform(y)
y_le[:5]

array([0, 0, 0, 0, 0])

In [ ]:
iris.info()
iris.describe()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   label         150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000